apiVersion: v1
kind: Pod
metadata:
  name: rdma-demo-1
spec:
  restartPolicy: OnFailure
  containers:
    - image: ir0cn/rdma-demo
      imagePullPolicy: IfNotPresent
      name: rdma-demo
      securityContext:
        capabilities:
          add: [ "IPC_LOCK" ]
      resources:
        limits:
          rdma/soft-roce: "1"
      command: [ "/bin/bash", "-c", "--", "trap : TERM INT; sleep infinity & wait" ]
---
apiVersion: v1
kind: Pod
metadata:
  name: rdma-demo-2
spec:
  restartPolicy: OnFailure
  containers:
    - image: ir0cn/rdma-demo
      imagePullPolicy: IfNotPresent
      name: rdma-demo
      securityContext:
        capabilities:
          add: [ "IPC_LOCK" ]
      resources:
        limits:
          rdma/soft-roce: "1"
      command: [ "/bin/bash", "-c", "--", "trap : TERM INT; sleep infinity & wait" ]
